# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Desktop\QTTool\src\Components\TableDataEditor\TableDataEditor.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_TableEditor(object):
    def setupUi(self, Form_TableEditor):
        Form_TableEditor.setObjectName("Form_TableEditor")
        Form_TableEditor.resize(1463, 782)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(Form_TableEditor)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(9, 9, 258, 43))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_file_path = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_file_path.setFont(font)
        self.label_file_path.setObjectName("label_file_path")
        self.horizontalLayout_2.addWidget(self.label_file_path)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.pushButton_AnylisisByLLM = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_AnylisisByLLM.setObjectName("pushButton_AnylisisByLLM")
        self.horizontalLayout_2.addWidget(self.pushButton_AnylisisByLLM)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form_TableEditor)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 80, 851, 109))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableWidget_Data = QtWidgets.QTableWidget(self.horizontalLayoutWidget)
        self.tableWidget_Data.setObjectName("tableWidget_Data")
        self.tableWidget_Data.setColumnCount(0)
        self.tableWidget_Data.setRowCount(0)
        self.verticalLayout.addWidget(self.tableWidget_Data)
        self.widget = QtWidgets.QWidget(self.horizontalLayoutWidget)
        self.widget.setObjectName("widget")
        self.verticalLayout.addWidget(self.widget)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.graphicsView_line = QtWidgets.QGraphicsView(self.horizontalLayoutWidget)
        self.graphicsView_line.setObjectName("graphicsView_line")
        self.horizontalLayout.addWidget(self.graphicsView_line)
        self.widget_2 = QtWidgets.QWidget(Form_TableEditor)
        self.widget_2.setGeometry(QtCore.QRect(80, 440, 811, 80))
        self.widget_2.setObjectName("widget_2")

        self.retranslateUi(Form_TableEditor)
        QtCore.QMetaObject.connectSlotsByName(Form_TableEditor)

    def retranslateUi(self, Form_TableEditor):
        _translate = QtCore.QCoreApplication.translate
        Form_TableEditor.setWindowTitle(_translate("Form_TableEditor", "Form"))
        self.label_file_path.setText(_translate("Form_TableEditor", "FilePath"))
        self.pushButton_AnylisisByLLM.setText(_translate("Form_TableEditor", "Anylisis By LLM"))
