# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Desktop\QTTool\src\UI\MainWorkspace.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWorkSpace(object):
    def setupUi(self, MainWorkSpace):
        MainWorkSpace.setObjectName("MainWorkSpace")
        MainWorkSpace.resize(775, 633)
        self.verticalLayout = QtWidgets.QVBoxLayout(MainWorkSpace)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mdiArea = QtWidgets.QMdiArea(MainWorkSpace)
        self.mdiArea.setObjectName("mdiArea")
        self.verticalLayout.addWidget(self.mdiArea)

        self.retranslateUi(MainWorkSpace)
        QtCore.QMetaObject.connectSlotsByName(MainWorkSpace)

    def retranslateUi(self, MainWorkSpace):
        _translate = QtCore.QCoreApplication.translate
        MainWorkSpace.setWindowTitle(_translate("MainWorkSpace", "Form"))
