# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\Desktop\QTTool\src\Components\Terminal\Terminal.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_Terminal(object):
    def setupUi(self, Form_Terminal):
        Form_Terminal.setObjectName("Form_Terminal")
        Form_Terminal.resize(616, 439)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form_Terminal)
        self.verticalLayout.setObjectName("verticalLayout")
        self.textEdit_Terminal = QtWidgets.QTextEdit(Form_Terminal)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.textEdit_Terminal.setFont(font)
        self.textEdit_Terminal.setObjectName("textEdit_Terminal")
        self.verticalLayout.addWidget(self.textEdit_Terminal)

        self.retranslateUi(Form_Terminal)
        QtCore.QMetaObject.connectSlotsByName(Form_Terminal)

    def retranslateUi(self, Form_Terminal):
        _translate = QtCore.QCoreApplication.translate
        Form_Terminal.setWindowTitle(_translate("Form_Terminal", "Form"))
