# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\Desktop\QTTool\src\Components\Terminal\Terminal.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_Terminal(object):
    def setupUi(self, Form_Terminal):
        Form_Terminal.setObjectName("Form_Terminal")
        Form_Terminal.resize(616, 439)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form_Terminal)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.textBrowser_ResultView = QtWidgets.QTextBrowser(Form_Terminal)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.textBrowser_ResultView.setFont(font)
        self.textBrowser_ResultView.setObjectName("textBrowser_ResultView")
        self.verticalLayout.addWidget(self.textBrowser_ResultView)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_current_dir = QtWidgets.QLabel(Form_Terminal)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_current_dir.setFont(font)
        self.label_current_dir.setObjectName("label_current_dir")
        self.horizontalLayout.addWidget(self.label_current_dir)
        self.lineEdit_Command = QtWidgets.QLineEdit(Form_Terminal)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_Command.setFont(font)
        self.lineEdit_Command.setObjectName("lineEdit_Command")
        self.horizontalLayout.addWidget(self.lineEdit_Command)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Form_Terminal)
        QtCore.QMetaObject.connectSlotsByName(Form_Terminal)

    def retranslateUi(self, Form_Terminal):
        _translate = QtCore.QCoreApplication.translate
        Form_Terminal.setWindowTitle(_translate("Form_Terminal", "Form"))
        self.label_current_dir.setText(_translate("Form_Terminal", "CurrentDir"))
